'use strict';
module.exports = function (config) {
    var sharedFiles = [

        // bower:js
        'bower_components/jquery/jquery.js',
        'bower_components/angular/angular.js',
        'bower_components/angular-animate/angular-animate.js',
        'bower_components/angular-base64/angular-base64.js',
        'bower_components/angular-cookies/angular-cookies.js',
        'bower_components/angular-gettext/dist/angular-gettext.js',
        'bower_components/angular-mocks/angular-mocks.js',
        'bower_components/angular-resource/angular-resource.js',
        'bower_components/angular-sanitize/angular-sanitize.js',
        'bower_components/angular-scroll/angular-scroll.js',
        'bower_components/angular-scroll-glue/src/scrollglue.js',
        'bower_components/angular-touch/angular-touch.js',
        'bower_components/angular-ui-bootstrap-bower/ui-bootstrap.min.js',
        'bower_components/angular-ui-router/release/angular-ui-router.js',
        'bower_components/bootstrap/dist/js/bootstrap.js',
        'bower_components/angular-strap/dist/angular-strap.min.js',
        'bower_components/angular-strap/dist/angular-strap.tpl.min.js',
        'bower_components/jquery-ui/ui/jquery-ui.js',
        'bower_components/oclazyload/dist/ocLazyLoad.js',
        'bower_components/robo-ui/dist/scripts/constants/robo.constants.js',
        'bower_components/robo-ui/dist/scripts/directives/robo.ui.backgroundImage.js',
        'bower_components/robo-ui/dist/scripts/directives/robo.ui.carousel.js',
        'bower_components/robo-ui/dist/scripts/directives/robo.ui.confirm.js',
        'bower_components/robo-ui/dist/scripts/directives/robo.ui.error.js',
        'bower_components/robo-ui/dist/scripts/directives/robo.ui.i18n.js',
        'bower_components/robo-ui/dist/scripts/directives/robo.ui.notify.js',
        'bower_components/robo-ui/dist/scripts/directives/robo.ui.numberPicker.js',
        'bower_components/robo-ui/dist/scripts/directives/robo.ui.popout.js',
        'bower_components/robo-ui/dist/scripts/directives/robo.ui.progressBarWidth.js',
        'bower_components/robo-ui/dist/scripts/directives/robo.ui.scrollable.js',
        'bower_components/robo-ui/dist/scripts/directives/robo.ui.select.js',
        'bower_components/robo-ui/dist/scripts/directives/robo.util.508.js',
        'bower_components/robo-ui/dist/scripts/factories/robo.util.dom.js',
        'bower_components/robo-ui/dist/scripts/factories/robo.util.LazyLoadService.js',
        'bower_components/robo-ui/dist/scripts/retro/zen-popout.js',
        'bower_components/robo-ui/dist/scripts/robo.ui.js',
        'bower_components/angular-dynamic-locale/dist/tmhDynamicLocale.js',
        'bower_components/moment/min/moment-with-locales.js',
        'bower_components/moment-timezone/builds/moment-timezone-with-data-2012-2022.js',
        'bower_components/engage-ui/dist/scripts/_retro/utilities/utilities.js',
        'bower_components/engage-ui/dist/scripts/_retro/widgets/errorWidget.js',
        'bower_components/engage-ui/dist/scripts/analytics/robo.analytics.js',
        'bower_components/engage-ui/dist/scripts/analytics/robo.api.analytics.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.accounts.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.avatar.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.combinator.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.config.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.connection.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.events.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.firstTimeExperience.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.healthProfile.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.idle.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.login.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.message.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.missions.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.profile.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.sharedService.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.sso.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.ssoOutAgreementService.js',
        'bower_components/engage-ui/dist/scripts/api/robo.api.survey.js',
        'bower_components/engage-ui/dist/scripts/api/robo.profile.helpers.js',
        'bower_components/engage-ui/dist/scripts/api/robo.session.js',
        'bower_components/engage-ui/dist/scripts/api/robo.util.clientSettingsService.js',
        'bower_components/engage-ui/dist/scripts/api/robo.util.cookies.js',
        'bower_components/engage-ui/dist/scripts/api/robo.util.url.js',
        'bower_components/engage-ui/dist/scripts/app/dino.js',
        'bower_components/engage-ui/dist/scripts/avatar/myAvatar.js',
        'bower_components/engage-ui/dist/scripts/chrome/controllers/robo.chrome.HeaderCtrl.js',
        'bower_components/engage-ui/dist/scripts/chrome/controllers/robo.chrome.NavCtrl.js',
        'bower_components/engage-ui/dist/scripts/chrome/directives/robo.chrome.clientLogo.js',
        'bower_components/engage-ui/dist/scripts/chrome/robo.chrome.js',
        'bower_components/engage-ui/dist/scripts/chrome/robo.footer.js',
        'bower_components/engage-ui/dist/scripts/constants/robo.constants.js',
        'bower_components/engage-ui/dist/scripts/dashboard/robo.dashboard.promoCards.js',
        'bower_components/engage-ui/dist/scripts/DOBGateway/robo.dobGateway.api.js',
        'bower_components/engage-ui/dist/scripts/DOBGateway/robo.dobGateway.component.js',
        'bower_components/engage-ui/dist/scripts/DOBGateway/robo.dobGateway.controller.js',
        'bower_components/engage-ui/dist/scripts/DOBGateway/robo.dobGateway.modal.controller.js',
        'bower_components/engage-ui/dist/scripts/DOBGateway/robo.dobGateway.modal.directive.js',
        'bower_components/engage-ui/dist/scripts/DOBGateway/robo.dobGateway.modal.helpers.js',
        'bower_components/engage-ui/dist/scripts/i18n/robo.api.i18n.js',
        'bower_components/engage-ui/dist/scripts/i18n/robo.i18n.CorporateService.js',
        'bower_components/engage-ui/dist/scripts/i18n/robo.i18n.js',
        'bower_components/engage-ui/dist/scripts/i18n/robo.i18n.SupportedLocales.js',
        'bower_components/engage-ui/dist/scripts/i18n/robo.LocalizationService.js',
        'bower_components/engage-ui/dist/scripts/i18n/robo.util.domain.js',
        'bower_components/engage-ui/dist/scripts/i18n/robo.util.i18n.js',
        'bower_components/engage-ui/dist/scripts/messages/robo.messages.js',
        'bower_components/engage-ui/dist/scripts/messages/robo.messages.NewMessageDialogCtrl.js',
        'bower_components/engage-ui/dist/scripts/messages/robo.messages.NewMessageDialogService.js',
        'bower_components/engage-ui/dist/scripts/registration/robo.registration.avatar.js',
        'bower_components/engage-ui/dist/scripts/security/robo.security.url.js',
        'bower_components/engage-ui/dist/scripts/ui/robo.ui-bootstrap.js',
        'bower_components/engage-ui/dist/scripts/ui/robo.ui.alignment.js',
        'bower_components/engage-ui/dist/scripts/ui/robo.ui.click.js',
        'bower_components/engage-ui/dist/scripts/ui/robo.ui.includeReplace.js',
        'bower_components/engage-ui/dist/scripts/ui/robo.ui.pod.js',
        'bower_components/engage-ui/dist/scripts/ui/robo.ui.roboUiSref.js',
        'bower_components/engage-ui/dist/scripts/ui/robo.ui.validate.js',
        'bower_components/engage-ui/dist/scripts/ui/robo.ui.whilePressed.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.address.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.applyAsync.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.cdn.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.coins.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.errSrc.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.followLink.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.legalUpdates.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.mobilePromotion.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.pagination.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.print.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.s3.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.scrollPosition.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.setBodyClass.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.ssoOutAuthModalCtrl.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.string.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.time.js',
        'bower_components/engage-ui/dist/scripts/util/robo.util.translatepostponed.js',
        'bower_components/jsTimezoneDetect/jstz.min.js',
        'bower_components/ng-flow/dist/ng-flow-standalone.js',
        // endbower
        'app/scripts/robo.progressPod.js',
        'app/scripts/**/*.js',
        'app/scripts/*.js',
        {pattern: 'test/mocks/*.js', included: true}
    ];

    return {
        basePath: '../../',
        frameworks: ['jasmine'],
        files: sharedFiles,
        setConfig: function(files) {
            config.set({
                basePath: '../../',
                files: sharedFiles.concat(files),
                frameworks: ['jasmine'],
                reporters: ['progress', 'coverage'],
                preprocessors: {
                    'app/scripts/**/*.js': ['coverage']
                },
                coverageReporter: {
                    type: 'lcovonly',
                    dir: 'test/coverage'
                }
            });
        }
    }
};
